name: CI build
on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Make
        run: sudo apt update && sudo apt install build-essential -y
      - name: Install golangci-lint
        run: GO111MODULE=on go get github.com/golangci/golangci-lint/cmd/golangci-lint@v1.25.1
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.14.1'
      - run: make release
      - uses: actions/upload-artifact@v1
        with:
          name: bellpush
          path: bellpush
      - uses: actions/upload-artifact@v1
        with:
          name: chime
          path: chime
