name: CI build
on: 
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Make
        run: sudo apt update && sudo apt install build-essential -y
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.14.1'
      - run: echo ${{ github.run_number }}
      - run: make build-bellpush build-chime
